### ISSUE TITLE
meta-lxatac-example Priority

### ISSUE THREAD

**Issue by userid0x0** [linux-automation/meta-lxatac#57]
Hi,
I am asking for your opinion here.
Does it make sense to mention that the the priority of the newly introduced `meta-lxatac-example` layer should be increased in order to be able to override `meta-lxatac-software`?

My usecase: I had to touch the `chrony` configuration.

**Comment by hnez** [comment]
Hi,

having the customization layer at the highest priority level makes sense. We do in fact have such an elevated priority for our Pengutronix-Internal customization layer:

```bash
$ bitbake-layers show-layers
NOTE: Starting bitbake server...
layer                 path                                      priority
==========================================================================
meta                  …/Projects/meta-lxatac/poky/meta          5
meta-poky             …/meta-lxatac/poky/meta-poky              5
meta-ptx              …/meta-lxatac/poky/../meta-ptx            6
meta-oe               …/meta-lxatac/poky/../meta-oe/meta-oe     5
…
meta-lxatac-ptx       …/meta-lxatac/poky/../meta-lxatac-ptx     11
```

I've created a PR to add notes about layer priorities to the README: #58.
Let's continue the discussion there.
